loading weights
945736
3000
[1.07478544 0.93044417]
  0%|          | 0/250 [00:00<?, ?it/s]  0%|          | 1/250 [00:11<48:05, 11.59s/it]Exception ignored in: <generator object tqdm.__iter__ at 0x7fdd77df5350>
Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    self.close()
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tqdm/std.py", line 1281, in close
    self.display(pos=0)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tqdm/std.py", line 1467, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tqdm/std.py", line 348, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tqdm/std.py", line 341, in fp_write
    fp.write(_unicode(s))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tqdm/utils.py", line 143, in inner
    return func(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 92, in new_write
    old_write(data)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/ipykernel/iostream.py", line 404, in write
    self.pub_thread.schedule(lambda : self._buffer.write(string))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/ipykernel/iostream.py", line 205, in schedule
    self._event_pipe.send(b'')
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/ipykernel/iostream.py", line 96, in _event_pipe
    try:
KeyboardInterrupt: 
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-cb5c897b46c5>", line 11, in <module>
    agent.learn()
  File "../src/agent.py", line 124, in learn
    critic_gradient = tape.gradient(critic_loss,
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 1080, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/eager/imperative_grad.py", line 71, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 162, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/math_grad.py", line 1695, in _MatMulGrad
    grad_b = gen_math_ops.mat_mul(a, grad, transpose_a=True)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5527, in mat_mul
    _result = pywrap_tfe.TFE_Py_FastPathExecute(
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2045, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 751, in getmodule
    f = getabsfile(module)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 720, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 702, in getsourcefile
    elif any(filename.endswith(s) for s in
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 702, in <genexpr>
    elif any(filename.endswith(s) for s in
KeyboardInterrupt

KeyboardInterrupt

