  0%|          | 0/100000 [00:00<?, ?it/s]  0%|          | 1/100000 [00:00<12:47:56,  2.17it/s]  0%|          | 2/100000 [00:05<90:33:50,  3.26s/it]  0%|          | 3/100000 [00:10<108:21:35,  3.90s/it]  0%|          | 4/100000 [00:19<171:16:19,  6.17s/it]  0%|          | 5/100000 [00:27<186:08:02,  6.70s/it]  0%|          | 6/100000 [00:39<233:08:31,  8.39s/it]  0%|          | 7/100000 [00:49<245:08:41,  8.83s/it]  0%|          | 8/100000 [00:57<245:42:59,  8.85s/it]  0%|          | 9/100000 [01:02<212:08:38,  7.64s/it]  0%|          | 10/100000 [01:37<440:58:34, 15.88s/it]  0%|          | 11/100000 [01:59<499:28:11, 17.98s/it]  0%|          | 12/100000 [02:16<486:21:30, 17.51s/it]  0%|          | 13/100000 [03:01<719:27:29, 25.90s/it]  0%|          | 14/100000 [03:38<808:13:25, 29.10s/it]  0%|          | 15/100000 [04:21<931:16:34, 33.53s/it]  0%|          | 16/100000 [05:05<1018:20:38, 36.67s/it]  0%|          | 17/100000 [05:50<1084:02:02, 39.03s/it]  0%|          | 18/100000 [06:20<1011:02:12, 36.40s/it]  0%|          | 19/100000 [07:04<1071:56:55, 38.60s/it]  0%|          | 20/100000 [07:47<1111:27:06, 40.02s/it]  0%|          | 21/100000 [08:31<1142:07:18, 41.13s/it]  0%|          | 22/100000 [09:13<1147:10:03, 41.31s/it]  0%|          | 23/100000 [09:56<1167:42:24, 42.05s/it]  0%|          | 24/100000 [10:41<1190:37:34, 42.87s/it]  0%|          | 25/100000 [11:26<1209:35:18, 43.56s/it]  0%|          | 26/100000 [12:15<1249:30:23, 44.99s/it]  0%|          | 27/100000 [13:00<1251:50:28, 45.08s/it]  0%|          | 28/100000 [13:44<1244:52:41, 44.83s/it]  0%|          | 29/100000 [14:16<1138:41:32, 41.00s/it]  0%|          | 30/100000 [15:03<1186:07:49, 42.71s/it]  0%|          | 31/100000 [15:51<1231:38:25, 44.35s/it]  0%|          | 31/100000 [16:29<886:38:00, 31.93s/it] 
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-8f485f7f2afa>", line 11, in <module>
    agent.learn()
  File "../src/agent.py", line 108, in learn
    new_q_value_0 = self.critic_0(states, new_policy_actions)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "../src/networks.py", line 21, in call
    state_action_value = self.dense_0(tf.concat([state, action], axis=1))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1207, in call
    return core_ops.dense(
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/keras/layers/ops/core.py", line 67, in dense
    outputs = activation(outputs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/keras/activations.py", line 306, in relu
    return K.relu(x, alpha=alpha, max_value=max_value, threshold=threshold)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/keras/backend.py", line 4706, in relu
    x = nn.relu(x)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 10463, in relu
    _result = pywrap_tfe.TFE_Py_FastPathExecute(
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2045, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 754, in getmodule
    os.path.realpath(f)] = module.__name__
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 391, in realpath
    path, ok = _joinrealpath(filename[:0], filename, {})
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 425, in _joinrealpath
    if not islink(newpath):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 167, in islink
    st = os.lstat(path)
KeyboardInterrupt
