2021-01-04 08:23:01,300 INFO    MainThread:2938789 [wandb_setup.py:_flush():70] setting env: {}
2021-01-04 08:23:01,301 INFO    MainThread:2938789 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-04 08:23:01,301 INFO    MainThread:2938789 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-04 08:23:01,301 INFO    MainThread:2938789 [wandb_init.py:_log_setup():303] Logging user logs to /home/anton/Projects/reinforcement_learning/ddqn/src/wandb/run-20210104_082301-1uuduvbp/logs/debug.log
2021-01-04 08:23:01,301 INFO    MainThread:2938789 [wandb_init.py:_log_setup():304] Logging internal logs to /home/anton/Projects/reinforcement_learning/ddqn/src/wandb/run-20210104_082301-1uuduvbp/logs/debug-internal.log
2021-01-04 08:23:02,698 INFO    MainThread:2938789 [wandb_run.py:_console_start():1237] atexit reg
2021-01-04 08:23:02,699 INFO    MainThread:2938789 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2021-01-04 08:23:02,702 INFO    MainThread:2938789 [wandb_run.py:_redirect():1107] Redirecting console.
2021-01-04 08:23:02,702 INFO    MainThread:2938789 [redirect.py:install():204] install start
2021-01-04 08:23:02,702 INFO    MainThread:2938789 [redirect.py:install():219] install stop
2021-01-04 08:23:02,702 INFO    MainThread:2938789 [redirect.py:install():204] install start
2021-01-04 08:23:02,703 INFO    MainThread:2938789 [redirect.py:install():219] install stop
2021-01-04 08:23:02,703 INFO    MainThread:2938789 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-04 08:30:24,977 INFO    MainThread:2938789 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-01-04 08:30:24,977 INFO    MainThread:2938789 [wandb_run.py:_restore():1179] restore
2021-01-04 08:30:24,977 INFO    MainThread:2938789 [redirect.py:uninstall():223] uninstall start
2021-01-04 08:30:24,978 INFO    MainThread:2938789 [redirect.py:_stop():278] _stop: stdout
2021-01-04 08:30:24,978 INFO    stdout    :2938789 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2021-01-04 08:30:24,978 INFO    stdout    :2938789 [redirect.py:_pipe_relay():136] relay done done: stdout
2021-01-04 08:30:24,978 INFO    MainThread:2938789 [redirect.py:_stop():284] _stop closed: stdout
2021-01-04 08:30:24,978 INFO    MainThread:2938789 [redirect.py:_stop():290] _stop joined: stdout
2021-01-04 08:30:24,979 INFO    MainThread:2938789 [redirect.py:_stop():292] _stop rd closed: stdout
2021-01-04 08:30:24,979 INFO    MainThread:2938789 [redirect.py:uninstall():227] uninstall done
2021-01-04 08:30:24,979 INFO    MainThread:2938789 [redirect.py:uninstall():223] uninstall start
2021-01-04 08:30:24,979 INFO    MainThread:2938789 [redirect.py:_stop():278] _stop: stderr
2021-01-04 08:30:24,979 INFO    MainThread:2938789 [redirect.py:_stop():284] _stop closed: stderr
2021-01-04 08:30:24,979 INFO    stderr    :2938789 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2021-01-04 08:30:24,979 INFO    stderr    :2938789 [redirect.py:_pipe_relay():136] relay done done: stderr
2021-01-04 08:30:24,980 INFO    MainThread:2938789 [redirect.py:_stop():290] _stop joined: stderr
2021-01-04 08:30:24,980 INFO    MainThread:2938789 [redirect.py:_stop():292] _stop rd closed: stderr
2021-01-04 08:30:24,980 INFO    MainThread:2938789 [redirect.py:uninstall():227] uninstall done
2021-01-04 08:30:24,982 INFO    MainThread:2938789 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "242c7f41b82e4f7da514264453f19e41"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 731
      total_bytes: 731
    }
  }
}

2021-01-04 08:30:26,990 INFO    MainThread:2938789 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "a86f84e978554ca5aeb8a380aeaac58b"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 9804
      total_bytes: 9804
    }
  }
}

2021-01-04 08:30:28,160 INFO    MainThread:2938789 [wandb_run.py:_show_files():1536] logging synced files
2021-01-04 08:30:28,162 INFO    MainThread:2938789 [internal.py:handle_exit():138] Internal process exited
